"""empty message

Revision ID: 73f285ef2df
Revises: 8e792980056
Create Date: 2014-02-22 16:10:49.895931

"""

# revision identifiers, used by Alembic.
revision = '73f285ef2df'
down_revision = '8e792980056'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
